apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ayd2g5/prueba:backend
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SWAGGER_HOST
              value: "34.121.52.166"   # tu IP estática backend
            - name: FLASK_RUN_HOST
              value: "0.0.0.0"
            - name: FLASK_RUN_PORT
              value: "5000"
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_DEBUG
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.121.52.166    # tu IP estática backend
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: backend
