FROM python:3.10-slim

# Para que los logs salgan al instante
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Instala deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código
COPY . .

# Expone el puerto 5000
EXPOSE 5000

# Arranca con Gunicorn apuntando a run.py:app
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "run:app"]
